### ISSUE TITLE
Trident: ClassCastException in StateTransitionMultiTracker

### ISSUE THREAD

**Issue by IvanRF** [kirill-grouchnikov/substance#19]
First posted on: https://github.com/Insubstantial/insubstantial/issues/146

I had this exception. It is not common, but it happens.

``` java
java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
    at java.util.HashMap$TreeNode.removeTreeNode(HashMap.java:2021)
    at java.util.HashMap.removeNode(HashMap.java:839)
    at java.util.HashMap.remove(HashMap.java:798)
    at org.pushingpixels.substance.internal.animation.StateTransitionMultiTracker$1.onFocusStateTransition(StateTransitionMultiTracker.java:91)
    at org.pushingpixels.substance.internal.animation.StateTransitionTracker.fireFocusStateTransitionEvent(StateTransitionTracker.java:723)
    at org.pushingpixels.substance.internal.animation.StateTransitionTracker.access$000(StateTransitionTracker.java:55)
    at org.pushingpixels.substance.internal.animation.StateTransitionTracker$2.onTimelineStateChanged(StateTransitionTracker.java:216)
    at org.pushingpixels.trident.Timeline$Chain.onTimelineStateChanged(Timeline.java:214)
    at org.pushingpixels.trident.TimelineEngine$1.run(TimelineEngine.java:591)
    at org.pushingpixels.trident.TimelineEngine$TimelineCallbackThread.run(TimelineEngine.java:242)
```

It was thrown when I started my application. But I only seen it two times (from thousands of executions). Also, I start seen it with Java 8 and latest Insubstantial version.

Nevertheless, the code on `StateTransitionMultiTracker` is still the same. I must add I didn't had this issue in a while (original post if from 17 Feb 2016).

**Comment by kirill-grouchnikov** [comment]
Not much actionable here. If this is happening under Substance 7.0, then it would be worth looking into.

**Comment by IvanRF** [comment]
Yes, I just post it as a reminder that Trident could throw this exception. As I said, I didn't see it again in a while.

**Comment by kirill-grouchnikov** [comment]
If this is happening under the latest dev builds, please reopen with the sample app that reproduces this issue.
