### ISSUE TITLE
alpha value out of range - appears

### ISSUE THREAD

**Issue by PirolA** [kirill-grouchnikov/substance#5]
Hello Kirill,

sometimes I got the following errormessage. What does it mean, can you help?

Best regards,
Pirol A.

java.lang.IllegalArgumentException: alpha value out of range
    at java.awt.AlphaComposite.<init>(Unknown Source)
    at java.awt.AlphaComposite.getInstance(Unknown Source)
    at java.awt.AlphaComposite.derive(Unknown Source)
    at org.pushingpixels.lafwidget.LafWidgetUtilities.getAlphaComposite(LafWidgetUtilities.java:615)
    at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.__org__pushingpixels__substance__internal__ui__SubstanceButtonUI__icon__paintIcon(SubstanceButtonUI.java:438)
    at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.paintIcon(SubstanceButtonUI.java)
    at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.paint(SubstanceButtonUI.java:345)
    at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.__org__pushingpixels__substance__internal__ui__SubstanceButtonUI__update(SubstanceButtonUI.java:491)
    at org.pushingpixels.substance.internal.ui.SubstanceButtonUI.update(SubstanceButtonUI.java)
    at javax.swing.JComponent.paintComponent(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at javax.swing.JComponent.paintChildren(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at javax.swing.JComponent.paintChildren(Unknown Source)
    at javax.swing.JComponent.paint(Unknown Source)
    at javax.swing.JComponent.paintToOffscreen(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
    at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
    at javax.swing.RepaintManager.paint(Unknown Source)
    at javax.swing.JComponent._paintImmediately(Unknown Source)
    at javax.swing.JComponent.paintImmediately(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
    at javax.swing.RepaintManager.seqPaintDirtyRegions(Unknown Source)
    at javax.swing.SystemEventQueueUtilities$ComponentWorkRequest.run(Unknown Source)
    at java.awt.event.InvocationEvent.dispatch(Unknown Source)
    at java.awt.EventQueue.dispatchEvent(Unknown Source)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
    at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by IvanRF** [comment]
@kirill-grouchnikov looking at the current code, this issue can be closed

**Comment by kirill-grouchnikov** [comment]
Please reopen if this is still happening under the latest dev builds with complete, small and standalone sample that reproduces this issue.
